version: "3.8"

services:
  app:
    image: node:18.17.0-alpine
    command: sh -c "yarn && yarn dev"
    working_dir: /app
    ports:
      - 3000
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app
